spring:
  datasource:
    url: jdbc:mysql://localhost:3306/szama?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  jackson:
    serialization:
      fail-on-empty-beans: false
